feat: adding error alarms to all the Lambda Functions
construct-catalog/catalog pull request #82
Opened 2021-01-21 03:02 UTC by mbonig

I added alarms to all the NodeFunctions that were being created. 

How it works:
The NodeFunction can now offer up an Errors metric from the [getErrorMetric method](https://github.com/construct-catalog/catalog/compare/master...mbonig:feat/alarms?expand=1#diff-1cda797d33458080aaf3ff9266cd398837840a10e7dc21cf64e3b53078ef9669R228). This will be the same basic object for all NodeFunctions. and has the following props:

```ts
    {
      unit: Unit.COUNT,
      label: `${this.node.scope?.node.id}-${this.node.id}`,
      period: Duration.minutes(1),
    }
```

These are then exposed by the scope of the NodeFunction (like `Ingestion`, `Renderer` and `Tweeter`) as an array of Metrics (e.g. [here](https://github.com/construct-catalog/catalog/compare/master...mbonig:feat/alarms?expand=1#diff-b9a9054426f32ca04dd2c5933088702a3dab815ba2d7b056ca7f2417874502b6R109)).

```ts
      lambdaErrorMetrics: [
        ...ingestion.lambdaErrorMetrics,
        ...tweeter.lambdaErrorMetrics,
        ...renderer.lambdaErrorMetrics
      ],
```

The Monitoring construct is then handed all of these metrics and starts rendering the [alarming components](https://github.com/construct-catalog/catalog/compare/master...mbonig:feat/alarms?expand=1#diff-e1d88f00f5bc7d43b3367d250758a3c9703c9f7d9ddc1492927826a2b80b4999R65):

```ts
    dashboard.addWidgets(
      new cloudwatch.GraphWidget({
        title: 'Lambda Errors',
        left: props.lambdaErrorMetrics,
        width: 24
      })
    );

    const alarmTopic = new Topic(this, 'alarm-topic', {
      displayName: 'All Construct Catalog alarm notifications'
    });

    if (props.slack) {
      const slackChannelConfiguration = new SlackChannelConfiguration(this, 'slack-notifications', {
        slackChannelConfigurationName: "construct-catalog",
        slackWorkspaceId: props.slack.workspaceId,
        slackChannelId: props.slack.channelId,
        notificationTopics: [ alarmTopic ],
      });
      slackChannelConfiguration.role?.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName("CloudWatchReadOnlyAccess"))
    }

    for (const metric of props.lambdaErrorMetrics){
      const alarm = new Alarm(this, `alarm-${metric.label}`, {
        metric: metric,
        threshold: 1,
        evaluationPeriods: 1,
        treatMissingData: TreatMissingData.NOT_BREACHING,
        actionsEnabled: true
      });
      alarm.addAlarmAction(new SnsAction(alarmTopic));
    }
```

This creates the alarms for each metric, with a 1/1 threshold/periods, missing data is non_breaching, but I think this should be reconsidered. It also creates the SNS Topic that alarms publish to, and the slackChannel setup, if provided in the env. If no slack setup is provided it's assumed that subscriptions will be setup manually.

In the case of [prod](https://github.com/construct-catalog/catalog/compare/master...mbonig:feat/alarms?expand=1#diff-dba67fbb6e0daeeb84b6dc651e451ea11b5bcdc4ed102cb49e4b2c4c1d4da64eR30), Slack is setup to go to:

```ts
  slack: {
    workspaceId: 'T017JQ2SWES', // cdk.dev
    channelId: 'C01K077KF5Z' // #cdk-catalog-hackathon
  },
```

2021-01-21 10:48 UTC, eladb requested changes

2021-01-21 10:48 UTC, eladb commented on packages/catalog/lib/util/node-function.ts
> +  public getErrorMetric(): cloudwatch.Metric {
Why not a property?

```ts
public get errorMetric(): cw.Metric { ... }
```

2021-01-21 10:48 UTC, eladb commented on packages/catalog/config.ts
> +    channelId: 'C01K077KF5Z' // #cdk-catalog-hackathon
Let's create a dedicated channel for #construct-catalog-alarms or something like that?

2021-01-21 10:48 UTC, eladb commented on packages/catalog/lib/monitoring/index.ts
> +        slackChannelConfigurationName: "construct-catalog",
Is `slackChannelConfigurationName` a required field?

2021-01-21 10:48 UTC, eladb commented on packages/catalog/stacks/catalog-stack.ts
> +      lambdaErrorMetrics: [
I am wondering if we can discover all `NodeFunction` constructs automatically and add them without having to expose `lambdaErrorMetrics`. Something like:

```ts
const lamdbaErrorMetrics = [];
for (const child of this.node.findAll()) {
  if (child instanceof NodeFunction) {
    lamdbaErrorMetrics.push(child.errorMetric);
  }
}
```

2021-01-21 17:05 UTC, mbonig commented on packages/catalog/lib/util/node-function.ts
> +  public getErrorMetric(): cloudwatch.Metric {
Because I forgot you could do that. =-} 

Pushed changes to turn it into a property.

2021-01-21 17:07 UTC, mbonig commented on packages/catalog/config.ts
> +    channelId: 'C01K077KF5Z' // #cdk-catalog-hackathon
added.

2021-01-21 17:09 UTC, mbonig commented on packages/catalog/lib/monitoring/index.ts
> +        slackChannelConfigurationName: "construct-catalog",
Looks like it, why?

2021-01-23 03:20 UTC, mbonig commented on packages/catalog/stacks/catalog-stack.ts
> +      lambdaErrorMetrics: [
good call. Made this change.

2021-01-25 16:10 UTC, eladb commented on packages/catalog/lib/monitoring/index.ts
> +        slackChannelConfigurationName: "construct-catalog",
Just curious about the API

2021-01-25 16:11 UTC, eladb commented on packages/catalog/stacks/catalog-stack.ts
> +    const lambdaErrorMetrics: Metric[] = [];
Nice!

2021-01-25 16:11 UTC, eladb approved these changes

2021-02-04 10:59 UTC, merged